version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: snippets  # Ensures the database is created
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure SQL script runs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d snippets -h db"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "6379:6379"

volumes:
  db_data:
